# -*- coding: utf-8 -*-
"""Refund Calculator .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RXJ0hC7fIURt2riIn3l7hK2Fd7-MaGvP
"""

def calculate_refund():
    print("=== Refund Calculator ===\n")

    # Step 1: Ask for total trip booking cost
    total_cost = float(input("Enter the total trip booking cost: $"))

    # Step 2: Ask for how much the client has actually paid
    total_paid = float(input("Enter the amount the client has actually paid: $"))

    # Step 3: Ask for the TPP (Trip Protection Plan) cost
    tpp = float(input("Enter the TPP (Trip Protection Plan) amount: $"))

    # Step 4: Ask for the deposit amount
    deposit = float(input("Enter the deposit amount: $"))

    # Step 5: Calculate 20% of the package cost
    twenty_percent = 0.20 * total_cost

    # Step 6: Calculate Total Non-Refundable (TNR)
    if deposit >= twenty_percent:
        tnr = tpp + deposit
    else:
        tnr = tpp + twenty_percent

    # Step 7: Calculate Refund
    refund = total_paid - tnr
    if refund < 0:
        refund = 0  # Prevent negative refunds

    # Output Results
    print("\n=== Calculation Summary ===")
    print(f"Total Package Cost: ${total_cost:.2f}")
    print(f"Total Paid: ${total_paid:.2f}")
    print(f"TPP: ${tpp:.2f}")
    print(f"Deposit: ${deposit:.2f}")
    print(f"20% of Package Cost: ${twenty_percent:.2f}")
    print(f"Total Non-Refundable (TNR): ${tnr:.2f}")
    print(f"Refund Due: ${refund:.2f}")

# Run the calculator
calculate_refund()